apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false" # [OPTIONAL] if not provided, will default to "false"
    clientID: "client_id" # [OPTIONAL available for version > 1.1.0] client id of the Azure AD Application or managed identity to use for workload identity
    keyvaultName: "kvname" # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret
        - |
          objectName: secret1
          objectType: secret
    tenantID: "tid"