apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  acme:
    email: omotayfere@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-cluster-issuer
    solvers:
      - selector: {}
        dns01:
          azureDNS:
            subscriptionID: "bb281e30-cd5c-4513-96a2-ea645adb3c64"
            resourceGroupName: "emart-zones"
            hostedZoneName: "xlice.com.ng"
            # Azure Cloud Environment, default to AzurePublicCloud
            environment: AzurePublicCloud
            # optional, only required if node pools have more than 1 managed identity assigned
            managedIdentity:
              # client id of the node pool managed identity (can not be set at the same time as resourceID)
              clientID: "1a495066-2f8d-403e-af12-d8878ca6df01"